const Classes = new Map([["CISC 3140","Overview of full-stack implementation of large scale web applications. Team-based software development methodologies, tools and practice. Introduction to modern HTML, CSS. Separation of structure, style and behavior. JavaScript, dynamic types, functional programming, prototypal classes, and closures. HTTP client-server communication, synchronous and asynchronous communication. Java Server Pages, simple database creation, programmatic queries and updates."],
["CISC 3142","An introduction to C++ and its roles providing support for object-oriented programming, generic programming, procedural programming, and low-level programming. The C++ memory model, and topics in explicit memory management. Storage classes, scope, and compilation stages. The Standard Template Library. Comparison with Java. (Not open to students who have completed Computer and Information Science 3110.)"],
["CISC 3160", "The design, implementation, and evolution of programming languages. Language features and their effects upon translation and run-time environments. Languages studied are chosen for their historical and current significance, programming paradigm, and run-time environment. Syntax and semantic specification; formal grammars."],
["CISC 3171", "A broad view of software engineering that introduces a variety of software engineering techniques that can be applied to practical software projects. Topics include: process models, software specification, software design, software development methods and tools, verification and validation, reliability, and human factors."],
["CISC 3220", "Algorithms, data structures, and their analysis. Applications for and solution to recurrence problems. Upper and lower bounds on complexities of various problems. Classification by design structures. Sorting methods, graph and selection algorithms. Pattern matching. Efficient computation of transitive closure and equivalences. NP-completeness."],
["ECON 2200", "Basic laws and principles of economic science. Value, price, and distribution. Preparation for more comprehensive studies involving application of the tools of analysis to economic problems. (This course is the same as Business 2200.)"],
["FINC 3310", "Understanding the goal and principles of financial management. Time value of money, bond valuation and stock valuation. Capital budgeting methods. Introduction to financial statement analysis, risk and return, asset pricing and capital structure analysis."],
["FINC 3330", "Characteristics of asset classes, securities, related markets and investment management companies. Principles of investment analysis including risk-return trade-off, asset pricing models, and the efficient market hypothesis. Legal and ethical issues in investment management. Evaluation of the risk-adjusted performance of investment portfolios. Introduction to derivatives, security analysis, and interest rate risk management to help students select electives that present advanced topics in investments. (Not open to students who have completed [Business 3330])."],
["ECON 3400", "Descriptive statistics including measures of central tendency, dispersion, and skewness. Probability and theoretical probability distributions including the binomial function and the normal curve. Sampling, estimation, and test of hypothesis. Simple correlation and regression analysis. Applications from social sciences. This course is the same as Business 3400. (Not open to students who are enrolled in or have completed any of the following equivalent courses: Sociology 2112; Psychology 3400.) STEM variant course - Satisfies Pathways Required Core Math and Quantitative Reasoning requirement."],
["BIOL 1002", "Cellular and molecular biology. Specific molecular process occurring in and around cells of evolutionarily diverse organisms. Biological concepts and theories of evolution, genetics, development, homeostasis, ecology-biodiversity, bioenergetics and bio-informatics. (Not open to students who have completed with a grade of C- or higher, the following course or courses: both Biology *2073 [17] and 2074 [17.1], or 1081 [4].). STEM variant course - Satisfies Pathways Required Core Life and Physical Sciences."],
["BIOL 3004", "Techniques for isolation, cultivation, and characterization of bacteria and the use of microbes as experimental organisms."],
["BIOL 3003", "Microbiology as a science, structure and function of microbes, microbial interrelationships, microbial metabolism, mechanisms of recombination, and microbes as agents of disease."],
["CHEM 2200", "Continuation of material from Chemistry 1200. Topics include kinetics, equilibrium, electrochemistry, and thermodynamics. Topics in inorganic, organic, and nuclear chemistry are also addressed. STEM variant course ? Satisfies Pathways Required Core Life and Physical Sciences. (Not open students who have completed Chem 2100)."],
["CHEM 2201", "Continuation of Chemistry 1201. Experiments involving quantitative measurements of kinetics, equilibria, and electrochemistry. An extensive unit on qualitative analysis is also included. (Not open to students who are enrolled in or have completed Chemistry 2100)."]]);

export default Classes